### PR TITLE
real-solar

### PR DESCRIPTION
**Pull request by tsliu01**
ggggg

### CODE REVIEW

**Comment by tsliu01** [comment]
ggggg

**Comment by tsliu01** [comment]
ddddd

**Comment by tsliu01** [comment]
gggg

**Comment by tsliu01** [comment]
dddd

**Comment by tsliu01** [comment]
ghgjg

**Comment by tsliu01** [comment]
fff

**Comment by tsliu01** [comment]
gggg

**Comment by tsliu01** [comment]
bbvbvb

**Comment by tsliu01** [comment]
hhhh

**Comment by tsliu01** [comment]
kkkk

**Comment by tsliu01** [comment]
ghghgh

**Comment by Charles651** [comment]
UI optimized

**Pull request merged**
